name: CI

on:
  # Triggers the workflow on push events to task_ branch
  push:
    branches: [ task_* ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.4

      - name: Build with Gradle
        run: ./gradlew build
        
      - name: Archive reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: build/reports/**
